# Generated by Django 3.2.9 on 2023-11-18 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0006_project_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
